



<div class="offcanvas offcanvas-end barrelateral" tabindex="-1" id="offcanvasRight" aria-labelledby="offcanvasRightLabel">
  <div class="offcanvas-header">
    <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <div class="offcanvas-body">
    <ul class="list-group box-wrap" style="text-transform: capitalize;" id="decoration">
        <h3 style="color:<?php echo $text_couleur ?>;"><?php if($langue === 'french'): ?>Thèmes basiques<?php endif; if($langue === 'english'): ?>Basic themes<?php endif; ?></h3>
        <a href="agriculture.php" class="btn box"><li style="background-color: <?php echo $couleur2 ?>; color:<?php echo $couleur ?>;" class="list-group-item"><?php if($langue === 'french'): ?>Agriculture<?php endif; if($langue === 'english'): ?>Agriculture<?php endif; ?></li></a>
        <a href="anatomie.php" class="btn box"><li style="background-color: <?php echo $couleur2 ?>; color:<?php echo $couleur ?>;" class="list-group-item"><?php if($langue === 'french'): ?>Anatomie - corps humain<?php endif; if($langue === 'english'): ?>Anatomy - human body<?php endif; ?></li></a>
        <a href="animaux.php" class="btn box"><li style="background-color: <?php echo $couleur2 ?>; color:<?php echo $couleur ?>;" class="list-group-item"><?php if($langue === 'french'): ?>Animaux<?php endif; if($langue === 'english'): ?>Animals<?php endif; ?></li></a>
        <a href="antonyme.php" class="btn box"><li style="background-color: <?php echo $couleur2 ?>; color:<?php echo $couleur ?>;" class="list-group-item"><?php if($langue === 'french'): ?>Antonyme<?php endif; if($langue === 'english'): ?>antonym<?php endif; ?></li></a>
        <a href="armes.php" class="btn box"><li style="background-color: <?php echo $couleur2 ?>; color:<?php echo $couleur ?>;" class="list-group-item"><?php if($langue === 'french'): ?>armes<?php endif; if($langue === 'english'): ?>weapons<?php endif; ?></li></a>
        <a href="astronomie.php" class="btn box"><li style="background-color: <?php echo $couleur2 ?>; color:<?php echo $couleur ?>;" class="list-group-item"><?php if($langue === 'french'): ?>astronomie<?php endif; if($langue === 'english'): ?>astronomy<?php endif; ?></li></a>
        <a href="banque.php" class="btn box"><li style="background-color: <?php echo $couleur2 ?>; color:<?php echo $couleur ?>;" class="list-group-item"><?php if($langue === 'french'): ?>banque<?php endif; if($langue === 'english'): ?>banking<?php endif; ?></li></a>
        <a href="boisson.php" class="btn box"><li style="background-color: <?php echo $couleur2 ?>; color:<?php echo $couleur ?>;" class="list-group-item"><?php if($langue === 'french'): ?>boisson<?php endif; if($langue === 'english'): ?>beverage<?php endif; ?></li></a>
        <a href="bricolage.php" class="btn box"><li style="background-color: <?php echo $couleur2 ?>; color:<?php echo $couleur ?>;" class="list-group-item"><?php if($langue === 'french'): ?>bricolage<?php endif; if($langue === 'english'): ?>DIY<?php endif; ?></li></a>
        <a href="catastrophe.php" class="btn box"><li style="background-color: <?php echo $couleur2 ?>; color:<?php echo $couleur ?>;" class="list-group-item"><?php if($langue === 'french'): ?>catastrophes naturelles<?php endif; if($langue === 'english'): ?>natural disasters<?php endif; ?></li></a>
        <a href="couleurs.php" class="btn box"><li style="background-color: <?php echo $couleur2 ?>; color:<?php echo $couleur ?>;" class="list-group-item"><?php if($langue === 'french'): ?>couleurs<?php endif; if($langue === 'english'): ?>colors<?php endif; ?></li></a>
        <a href="ecole.php" class="btn box"><li style="background-color: <?php echo $couleur2 ?>; color:<?php echo $couleur ?>;" class="list-group-item"><?php if($langue === 'french'): ?>école<?php endif; if($langue === 'english'): ?>school<?php endif; ?></li></a>
        <a href="elementschimiques.php" class="btn box"><li style="background-color: <?php echo $couleur2 ?>; color:<?php echo $couleur ?>;" class="list-group-item"><?php if($langue === 'french'): ?>éléments chimiques et autres matières<?php endif; if($langue === 'english'): ?>chemical elements and other matters<?php endif; ?></li></a>
        <a href="epices.php" class="btn box"><li style="background-color: <?php echo $couleur2 ?>; color:<?php echo $couleur ?>;" class="list-group-item"><?php if($langue === 'french'): ?>épices<?php endif; if($langue === 'english'): ?>spices<?php endif; ?></li></a>
        <a href="famille.php" class="btn box"><li style="background-color: <?php echo $couleur2 ?>; color:<?php echo $couleur ?>;" class="list-group-item"><?php if($langue === 'french'): ?>famille<?php endif; if($langue === 'english'): ?>family<?php endif; ?></li></a>
        <a href="fitness.php" class="btn box"><li style="background-color: <?php echo $couleur2 ?>; color:<?php echo $couleur ?>;" class="list-group-item"><?php if($langue === 'french'): ?>fitness<?php endif; if($langue === 'english'): ?>fitness<?php endif; ?></li></a>
        <a href="formegeo.php" class="btn box"><li style="background-color: <?php echo $couleur2 ?>; color:<?php echo $couleur ?>;" class="list-group-item"><?php if($langue === 'french'): ?>formes géométriques<?php endif; if($langue === 'english'): ?>geometric shapes<?php endif; ?></li></a>
        <a href="fruits.php" class="btn box"><li style="background-color: <?php echo $couleur2 ?>; color:<?php echo $couleur ?>;" class="list-group-item"><?php if($langue === 'french'): ?>fruits<?php endif; if($langue === 'english'): ?>fruits<?php endif; ?></li></a>
        <a href="geographie.php" class="btn box"><li style="background-color: <?php echo $couleur2 ?>; color:<?php echo $couleur ?>;" class="list-group-item"><?php if($langue === 'french'): ?>géographie<?php endif; if($langue === 'english'): ?>geography<?php endif; ?></li></a>
        <a href="histoire.php" class="btn box"><li style="background-color: <?php echo $couleur2 ?>; color:<?php echo $couleur ?>;" class="list-group-item"><?php if($langue === 'french'): ?>histoire<?php endif; if($langue === 'english'): ?>history<?php endif; ?></li></a>
        <a href="loisirs.php" class="btn box"><li style="background-color: <?php echo $couleur2 ?>; color:<?php echo $couleur ?>;" class="list-group-item"><?php if($langue === 'french'): ?>loisirs<?php endif; if($langue === 'english'): ?>hobbies<?php endif; ?></li></a>
        <a href="insecte.php" class="btn box"><li style="background-color: <?php echo $couleur2 ?>; color:<?php echo $couleur ?>;" class="list-group-item"><?php if($langue === 'french'): ?>insecte<?php endif; if($langue === 'english'): ?>insect<?php endif; ?></li></a>
        <a href="legumes.php" class="btn box"><li style="background-color: <?php echo $couleur2 ?>; color:<?php echo $couleur ?>;" class="list-group-item"><?php if($langue === 'french'): ?>légumes<?php endif; if($langue === 'english'): ?>vegetables<?php endif; ?></li></a>
        <a href="5sens.php" class="btn box"><li style="background-color: <?php echo $couleur2 ?>; color:<?php echo $couleur ?>;" class="list-group-item"><?php if($langue === 'french'): ?>5 sens<?php endif; if($langue === 'english'): ?>the 5 senses<?php endif; ?></li></a>
        <a href="devise.php" class="btn box"><li style="background-color: <?php echo $couleur2 ?>; color:<?php echo $couleur ?>;" class="list-group-item"><?php if($langue === 'french'): ?>devises<?php endif; if($langue === 'english'): ?>currencies<?php endif; ?></li></a>
        <a href="jours.php" class="btn box"><li style="background-color: <?php echo $couleur2 ?>; color:<?php echo $couleur ?>;" class="list-group-item"><?php if($langue === 'french'): ?>jours - mois - saisons<?php endif; if($langue === 'english'): ?>days - months - seasons<?php endif; ?></li></a>
        <a href="materiaux.php" class="btn box"><li style="background-color: <?php echo $couleur2 ?>; color:<?php echo $couleur ?>;" class="list-group-item"><?php if($langue === 'french'): ?>les matériaux<?php endif; if($langue === 'english'): ?>materials<?php endif; ?></li></a>
        <a href="merveilles.php" class="btn box"><li style="background-color: <?php echo $couleur2 ?>; color:<?php echo $couleur ?>;" class="list-group-item"><?php if($langue === 'french'): ?>les merveilles du monde<?php endif; if($langue === 'english'): ?>the world's wonders<?php endif; ?></li></a>
        <a href="signes.php" class="btn box"><li style="background-color: <?php echo $couleur2 ?>; color:<?php echo $couleur ?>;" class="list-group-item"><?php if($langue === 'french'): ?>les signes astrologiques<?php endif; if($langue === 'english'): ?>astrological signs<?php endif; ?></li></a>
        <a href="maison.php" class="btn box"><li style="background-color: <?php echo $couleur2 ?>; color:<?php echo $couleur ?>;" class="list-group-item"><?php if($langue === 'french'): ?>maison<?php endif; if($langue === 'english'): ?>house<?php endif; ?></li></a>
        <a href="mariage.php" class="btn box"><li style="background-color: <?php echo $couleur2 ?>; color:<?php echo $couleur ?>;" class="list-group-item"><?php if($langue === 'french'): ?>mariage<?php endif; if($langue === 'english'): ?>wedding<?php endif; ?></li></a>
        <a href="maquillage.php" class="btn box"><li style="background-color: <?php echo $couleur2 ?>; color:<?php echo $couleur ?>;" class="list-group-item"><?php if($langue === 'french'): ?>maquillage<?php endif; if($langue === 'english'): ?>make-up<?php endif; ?></li></a>
        <a href="meteo.php" class="btn box"><li style="background-color: <?php echo $couleur2 ?>; color:<?php echo $couleur ?>;" class="list-group-item"><?php if($langue === 'french'): ?>météo<?php endif; if($langue === 'english'): ?>weather<?php endif; ?></li></a>
        <a href="metiers.php" class="btn box"><li style="background-color: <?php echo $couleur2 ?>; color:<?php echo $couleur ?>;" class="list-group-item"><?php if($langue === 'french'): ?>métiers<?php endif; if($langue === 'english'): ?>jobs<?php endif; ?></li></a>
        <a href="motdeliaison.php" class="btn box"><li style="background-color: <?php echo $couleur2 ?>; color:<?php echo $couleur ?>;" class="list-group-item"><?php if($langue === 'french'): ?>mots de liaison<?php endif; if($langue === 'english'): ?>linking words<?php endif; ?></li></a>
        <a href="moyensdetransport.php" class="btn box"><li style="background-color: <?php echo $couleur2 ?>; color:<?php echo $couleur ?>;" class="list-group-item"><?php if($langue === 'french'): ?>moyens de transport<?php endif; if($langue === 'english'): ?>means of transport<?php endif; ?></li></a>
        <a href="musique.php" class="btn box"><li style="background-color: <?php echo $couleur2 ?>; color:<?php echo $couleur ?>;" class="list-group-item"><?php if($langue === 'french'): ?>musique & instrument<?php endif; if($langue === 'english'): ?>music & instrument<?php endif; ?></li></a>
        <a href="nature.php" class="btn box"><li style="background-color: <?php echo $couleur2 ?>; color:<?php echo $couleur ?>;" class="list-group-item"><?php if($langue === 'french'): ?>nature<?php endif; if($langue === 'english'): ?>nature<?php endif; ?></li></a>
        <a href="nourriture.php" class="btn box"><li style="background-color: <?php echo $couleur2 ?>; color:<?php echo $couleur ?>;" class="list-group-item"><?php if($langue === 'french'): ?>nourriture & alimentation<?php endif; if($langue === 'english'): ?>food<?php endif; ?></li></a>
        <a href="nombre.php" class="btn box"><li style="background-color: <?php echo $couleur2 ?>; color:<?php echo $couleur ?>;" class="list-group-item"><?php if($langue === 'french'): ?>nombre<?php endif; if($langue === 'english'): ?>numbers<?php endif; ?></li></a>
        <a href="oiseaux.php" class="btn box"><li style="background-color: <?php echo $couleur2 ?>; color:<?php echo $couleur ?>;" class="list-group-item"><?php if($langue === 'french'): ?>oiseaux<?php endif; if($langue === 'english'): ?>birds<?php endif; ?></li></a>
        <a href="pays.php" class="btn box"><li style="background-color: <?php echo $couleur2 ?>; color:<?php echo $couleur ?>;" class="list-group-item"><?php if($langue === 'french'): ?>pays<?php endif; if($langue === 'english'): ?>countries<?php endif; ?></li></a>
        <a href="qualitedefaut.php" class="btn box"><li style="background-color: <?php echo $couleur2 ?>; color:<?php echo $couleur ?>;" class="list-group-item"><?php if($langue === 'french'): ?>qualités & défauts<?php endif; if($langue === 'english'): ?>quality & flaws<?php endif; ?></li></a>
        <a href="quantite.php" class="btn box"><li style="background-color: <?php echo $couleur2 ?>; color:<?php echo $couleur ?>;" class="list-group-item"><?php if($langue === 'french'): ?>quantité<?php endif; if($langue === 'english'): ?>quantity<?php endif; ?></li></a>
        <a href="sentiments.php" class="btn box"><li style="background-color: <?php echo $couleur2 ?>; color:<?php echo $couleur ?>;" class="list-group-item"><?php if($langue === 'french'): ?>sentiments & émotions<?php endif; if($langue === 'english'): ?>feelings & emotions<?php endif; ?></li></a>
        <a href="sport.php" class="btn box"><li style="background-color: <?php echo $couleur2 ?>; color:<?php echo $couleur ?>;" class="list-group-item"><?php if($langue === 'french'): ?>sport<?php endif; if($langue === 'english'): ?>sport<?php endif; ?></li></a>
        <a href="temps.php" class="btn box"><li style="background-color: <?php echo $couleur2 ?>; color:<?php echo $couleur ?>;" class="list-group-item"><?php if($langue === 'french'): ?>temps<?php endif; if($langue === 'english'): ?>time<?php endif; ?></li></a>
        <a href="vetement.php" class="btn box"><li style="background-color: <?php echo $couleur2 ?>; color:<?php echo $couleur ?>;" class="list-group-item"><?php if($langue === 'french'): ?>vêtement<?php endif; if($langue === 'english'): ?>clothing<?php endif; ?></li></a>
        <a href="ville.php" class="btn box"><li style="background-color: <?php echo $couleur2 ?>; color:<?php echo $couleur ?>;" class="list-group-item"><?php if($langue === 'french'): ?>ville<?php endif; if($langue === 'english'): ?>city<?php endif; ?></li></a>
        <a href="voyage.php" class="btn box"><li style="background-color: <?php echo $couleur2 ?>; color:<?php echo $couleur ?>;" class="list-group-item"><?php if($langue === 'french'): ?>voyage<?php endif; if($langue === 'english'): ?>traveling<?php endif; ?></li></a>

        <br><h3 style="color:<?php echo $text_couleur ?>;"><?php if($langue === 'french'): ?>Thèmes Professionnels<?php endif; if($langue === 'english'): ?>Professional themes<?php endif; ?></h3>
        <a href="comptabilite.php" class="btn box"><li style="background-color: <?php echo $couleur2 ?>; color:<?php echo $couleur ?>;" class="list-group-item"><?php if($langue === 'french'): ?>comptabilité & gestion<?php endif; if($langue === 'english'): ?>accounting & management<?php endif; ?></li></a>
        <a href="droit.php" class="btn box"><li style="background-color: <?php echo $couleur2 ?>; color:<?php echo $couleur ?>;" class="list-group-item"><?php if($langue === 'french'): ?>droit<?php endif; if($langue === 'english'): ?>law<?php endif; ?></li></a>
        <a href="economie.php" class="btn box"><li style="background-color: <?php echo $couleur2 ?>; color:<?php echo $couleur ?>;" class="list-group-item"><?php if($langue === 'french'): ?>économie<?php endif; if($langue === 'english'): ?>economy<?php endif; ?></li></a>
        <a href="entrepriseentretien.php" class="btn box"><li style="background-color: <?php echo $couleur2 ?>; color:<?php echo $couleur ?>;" class="list-group-item"><?php if($langue === 'french'): ?>entreprise & entretien<?php endif; if($langue === 'english'): ?>company & interview<?php endif; ?></li></a>
        <a href="finance.php" class="btn box"><li style="background-color: <?php echo $couleur2 ?>; color:<?php echo $couleur ?>;" class="list-group-item"><?php if($langue === 'french'): ?>finance<?php endif; if($langue === 'english'): ?>finance<?php endif; ?></li></a>
        <a href="industrie.php" class="btn box"><li style="background-color: <?php echo $couleur2 ?>; color:<?php echo $couleur ?>;" class="list-group-item"><?php if($langue === 'french'): ?>industrie<?php endif; if($langue === 'english'): ?>industry<?php endif; ?></li></a>
        <a href="informatique.php" class="btn box"><li style="background-color: <?php echo $couleur2 ?>; color:<?php echo $couleur ?>;" class="list-group-item"><?php if($langue === 'french'): ?>informatique<?php endif; if($langue === 'english'): ?>informatique<?php endif; ?></li></a>
        <a href="marketing.php" class="btn box"><li style="background-color: <?php echo $couleur2 ?>; color:<?php echo $couleur ?>;" class="list-group-item"><?php if($langue === 'french'): ?>marketing<?php endif; if($langue === 'english'): ?>marketing<?php endif; ?></li></a>
        <a href="politique.php" class="btn box"><li style="background-color: <?php echo $couleur2 ?>; color:<?php echo $couleur ?>;" class="list-group-item"><?php if($langue === 'french'): ?>politique & gouvernance<?php endif; if($langue === 'english'): ?>politics & governance<?php endif; ?></li></a>
        <a href="unitesdemesure.php" class="btn box"><li style="background-color: <?php echo $couleur2 ?>; color:<?php echo $couleur ?>;" class="list-group-item"><?php if($langue === 'french'): ?>science & unités de mesure<?php endif; if($langue === 'english'): ?>science & units of measure<?php endif; ?></li></a>
    </ul>
  </div>
</div>